language: node_js
node_js: 8
git:
  depth: 3
  submodules: true
before_install:
- echo $GITHUB_DEPLOY_KEY
- echo $GITHUB_DEPLOY_KEY > ~/.ssh/github-deploy-key
# - ssh-add ~/.ssh/github-deploy-key
# - cat ~/.ssh/github-deploy-key
- git clone git@github.com:liuyanjie/liuyanjie.github.io.git
install: true
before_script: true
script: true
after_script: true
before_deploy: true
deploy:
  skip_cleanup: true
after_deploy: true
after_success: true
after_failure: true
